DESTDIR=`pwd`/debian/wavegain

all:
	gcc *.c -o wavegain -DHAVE_CONFIG_H -lm -lsndfile

install:
	install -d $(DESTDIR)/usr/bin/
	install -m 0755 wavegain $(DESTDIR)/usr/bin/

clean:
	rm -Rf wavegain *.o
