.TH WAVEGAIN 1 "October  17, 2012"

.SH NAME
wavegain \- apply ReplayGain algorithm to PCM wave files

.SH SYNOPSIS
.B wavegain
.RI [ OPTIONS ] " FILE..."

.SH OPTIONS

.TP
.B \-h, \-\-help
Print the help information.


.TP
.B \-c, \-\-calculate
Calculate and print gain settings and DC Offsets, but not do not apply them
(DEFAULT)


.TP
.B \-s, \-\-fast
Similar to -\-calculate, but only only analyzes 8,192,000 samples per file.
Results will not be as accurate as a full analysis but with most material will
be within +/\- 0.5db.
.br
DC Offset will not be calculated.

.TP
.B \-y, \-\-apply
Calculates and applies gain settings and DC Offset correction.


.TP
.B \-r, \-\-radio
When used with \-\-apply, use ReplayGain Radio/Single Track gain setting (DEFAULT)

Analyses the ReplayGain values for each of the tracks (files) specified on an
individual basis.


.TP
.B \-a, \-\-album
When used with \-\-apply, use ReplayGain Album/Audiophile gain setting.

Analyses the ReplayGain values for each of the tracks (files) specified and
collectively for the whole selection. The album gain value, if applied, ensures
that all tracks are adjusted by the same scaling factor and so retain the same
relative level of loudness.


.TP
.B \-q, \-\-adc
When used with \-\-apply, apply Album-based DC Offset correction.
The default is to apply Track-based DC Offset correction.


.TP
.B \-p, \-\-no_offset
Do not apply any DC Offset correction.


.TP
.B \-x, \-\-scale
Write scale values to stdout in the format: n.nnnnnn
.br
In Album mode it only writes the Album Scale value, and
in Title mode it only writes the Title Scale values.
.br
Only works with \-\-calculate (calculation-only mode)


.TP
.B \-w, \-\-write
When used with \-\-apply, additionally write a 'gain' chunk into the Wave Header,
storing the scalefactor applied to the wave data as a double floating point number.
.br
This header is required for the '\-\-undo\-gain' feature, and its presence will
also will also skip future re-processing of the affected file(s), unless '\-\-force' is used.


.TP
.B \-\-force
Force the reprocessing of a file even if it contains a that contains a 'gain' chunk
(previously created using \-\-write)


.TP
.B \-\-undo\-gain
Read the scalefactor in the 'gain' chunk and uses the value to reverse the
previously applied gain. This will not recreate a bit identical version of the
original file, but it will be rescaled to the original level.


.TP
.B \-z, \-\-recursive
Search for files recursively, each folder as an album


.TP
.B \-l, \-\-log
Write a log file. (Default filename = WGLog.txt)


.TP
.B \-f, \-\-logfile
Specify log filename. Assumes \-\-log


.TP
.B \-n, \-\-noclip
Do not prevent clipping. The default is to prevent clipping.


.TP
.BI "\-d" x ", \-\-dither=" x
.RI "Dither output, where " x " is:"
  0  for dither OFF (default).
  1  for dither without Noise Shaping.
  2  for dither with Light  Noise Shaping.
  3  for dither with Medium Noise Shaping.
  4  for dither with Heavy  Noise Shaping.


.TP
.B \-t, \-\-limiter
Apply 6dB Hard Limiter to output.


.TP
.BI "\-g" x ", \-\-gain=" x
.RI "Apply additional Manual Gain adjustment in decibels, where " x
is any floating point number between
.BR \-20.0 " and " +12.0
.br
Clipping Prevention will be applied unless \-\-noclip is used.


.TP
.B \-o, \-\-stdout
Write output file to stdout.

.TP
.BI "\-b" x ", \-\-bits=" x
.RI "Set output sample format, where " x "is:"
  1  for  8 bit unsigned PCM data.
  2  for 16 bit signed PCM data
  3  for 24 bit signed PCM data.
  4  for 32 bit signed PCM data.
  5  for 32 bit floats.
  6  for 16 bit 'aiff' format.

By default, the output file will be of the same bitwidth and type as the input file.

.SH FILES
WaveGain input files may be 8, 16, 24 or 32 bit integer, or floating point
wave files with 1 or 2 channels and a sample rate of 96000Hz, 88200Hz,
64000Hz, 48000Hz, 44100Hz, 32000Hz, 24000Hz, 22050Hz, 16000Hz, 12000Hz,
11025Hz or 8000Hz. 16 bit integer 'aiff' files are also supported.

Use '\-' as filename for stdin input.

.SH AUTHOR
wavegain was written by John Edwards <john.edwards33@ntlworld.com>
.br
Additional code by Magnus Holmgren, Gian\-Carlo Pascutto, and Tycho.

.PP
This manual page was written by Rodrigo Silva <linux@rodrigosilva.com>,
for the Debian project (and may be used by others).
